# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMplIDiLX4_6BCAaaLE8Cp2lDuJPyIUR
"""

import streamlit as st

st.title("Hello Streamlit!")
st.write("This is a simple test to check if Streamlit is working.")